Telephoenix/config/routes.rb
Telephoenix::Application.routes.draw do

  match 'auth/:provider/callback', to: 'omniauth#create'
  match 'auth/failure', to: redirect('/')
  

  get "static_pages/about"

  get "static_pages/contact"

  get "static_pages/home"

  resources :likes

  get "user/register"
  post "user/register"

  get "user/login"
  post "user/login"

  get "user/logout"

  get "user/delete"

  get "user/edit"

  get "user/forget_password"   
  post "user/forget_password"

  get "user/upgrade"
  post "user/upgrade"

  get "user/indexMod"
  get "user/indexAdmin"
  
  resources :user do
    member do
      get 'change_password'
      post 'change_password'
    end
  end

  

  
resources :phones do
    resources :reviews do
        resources :comments
    end
end

match "/review_likes/new/:review_id/:value"=> "review_likes#new"
resources :review_likes

resources :user

root to: redirect('/phones')
end

Telephoenix/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  respond_to :html
  
  before_filter :login_required, :only=>['new','create']

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
    @can_edit = can_edit(@review.user)
    @comments = Comment.find_all_by_review_id(params[:id])
  end

  def new
    @phone = Phone.find(params[:phone_id])
    @user = current_user
    if Review.find_by_phone_id_and_user_id(@phone, @user) != nil
      flash[:warning] = "You can only write one review per phone"
      redirect_to phone_path(@phone)
    else      
      @review = @phone.reviews.build
      @review.user = @user   
      respond_with(@review)
      
    end
  end

  def create   
    @phone = Phone.find(params[:phone_id])
    @user = current_user
    @review = @phone.reviews.build(params[:review])
    @review.user = @user
    @review.num_likes =0
    @review.num_dislikes =0
    @review.save!
    redirect_to phone_path(@phone)
  end

  def edit
    @review = Review.find(params[:id])
    @can_edit = can_edit(@review.user)
    if @can_edit
      respond_with(@review)  
    else
      flash[:warning] = "You cannot edit this review!"
      redirect_to phone_review_path(@review.phone, @review)
    end
  end

  def update
    @review = Review.find(params[:id])
    @review.update_attributes!(params[:review])
    redirect_to phone_review_path(@review.phone, @review)
  end



  def destroy
    review = Review.find(params[:id])
    @can_edit = can_edit(review.user)
    if @can_edit
      phone = review.phone
      comments = Comment.find(:all, :from => "Comments", :conditions => ['review_id = ?',review.id])
      comments.each { |comment|
      comment.destroy}
      review.destroy
      flash[:message] = "The review has been deleted."
      redirect_to phone_path(phone)
    else
      flash[:warning] = "You cannot delete this review!"
      redirect_to phone_review_path(review.phone, review)
    end
  end

end

Telephoenix/app/views/reviews/edit.html.haml
%h2 Edit Review

= form_tag phone_review_path(@review), method: :put do
  = label :review, :rating, 'Rating'
  = select :review, :rating, (1..10)

  = label :review, :review_text, 'Review'
  = text_area :review, :review_text, :cols => 80, :rows => 20

  = submit_tag 'Save Changes'
  

Telephoenix/app/views/reviews/index.html.haml
%h2 Reviews

%table#reviews
  %thead
    %tr
      %th User
      %th Phone
      %th Rating
  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.user
        %td= review.phone
        %td= review.rating

Telephoenix/app/views/reviews/new.html.haml
%h2 New Review

= form_tag phone_reviews_path, method: :post do
  = label :review, :rating, 'Rating'
  = select :review, :rating, (1..10)

  = label :review, :review_text, 'Review'
  = text_area :review, :review_text, :cols => 80, :rows => 20

  = submit_tag 'Save'
  

				

Telephoenix/app/views/reviews/show.html.haml
%h2 Review
%div
  %div{:style => "float:left"}
    = button_to "Back", {:controller => "phones", :action => "show" }, :method => :get
%div{:style => "clear:both"}
%p

%table{:style => "width: 50%; height: 40%"}
  %tr
    %th{:align => "left"} 
      %b= @review.user.username.to_s + ": "
  %tr
    %th
  %tbody
    %tr{:valign => "top"}
      %td
        %dl
          %dt
            %dd
              = "Rating: "
              = @review.rating.to_s
            %dd
              = @review.review_text 
          %dl
            %dt
              %p
              %dd
              - current_user = User.find_by_id(session[:user_id])
              - if (current_user != nil && @can_edit)
                %div
                  %div{:style => "float:left"}
                    = button_to "Edit Review", {:controller => "reviews", :action => "edit" }, :method => :get
                  %div{:style => "float:left"}
                    = "|"
                  %div{:style => "float:left"}
                    = button_to "Delete Review", phone_review_path(@review.phone, @review), :method => :delete, confirm: 'Are you sure?'
                %div{:style => "clear:both" }
%table#comments
  %col{:width => "200px"}/
  %thead
    %tr
      %div
        %div{:style => "float:left" }
          %th
            = button_to "New Comment", new_phone_review_comment_path(@review.phone, @review), :method => :get
      %div{:style => "clear:both" }

    %tbody
      - @comments.each do |comment|
        %tr
          %td= comment.user.user_type.to_s
          %td
            = link_to comment.user.username.to_s, user_path(comment.user) 
            = "Says:"
        %tr  
          %td= "\t"
          %td= comment.comment_text

        - if (current_user != nil && (current_user == comment.user || moder? || admin?))
          %td= "\t"
          %td= button_to "Edit", edit_phone_review_comment_path(@review.phone, @review, comment), :method => :get
          %td= button_to "Delete", phone_review_comment_path(@review, comment), method: :delete, confirm: 'Are you sure?'