Telephoenix/config/routes.rb
Telephoenix::Application.routes.draw do

  match 'auth/:provider/callback', to: 'omniauth#create'
  match 'auth/failure', to: redirect('/')
  

  get "static_pages/about"

  get "static_pages/contact"

  get "static_pages/home"

  resources :likes

  get "user/register"
  post "user/register"

  get "user/login"
  post "user/login"

  get "user/logout"

  get "user/delete"

  get "user/edit"

  get "user/forget_password"   
  post "user/forget_password"

  get "user/upgrade"
  post "user/upgrade"

  get "user/indexMod"
  get "user/indexAdmin"
  
  resources :user do
    member do
      get 'change_password'
      post 'change_password'
    end
  end

  

  
resources :phones do
    resources :reviews do
        resources :comments
    end
end

match "/review_likes/new/:review_id/:value"=> "review_likes#new"
resources :review_likes

resources :user

root to: redirect('/phones')
end

Telephoenix/app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  has_many :reviews
  #make_flaggable :flag_once => true
  mount_uploader :image, ImageUploader
  make_flagger
  attr_accessible :username, :email, :password, :password_confirmation, :ip_address, :image
  attr_protected :id, :salt, :user_type
  attr_accessor :password, :password_confirmation, :current_password, :password_validator, :username_validator #determine whether validate password/username

  validates_length_of :username, :within => 5..40, :if => :should_validate_username?   
  validates_presence_of :username, :if => :should_validate_username?    
  validates_uniqueness_of :username, :if => :should_validate_username?    
  
  validates_length_of :password, :within => 5..40,  :if => :should_validate_password?   
  validates_presence_of :password, :password_confirmation, :salt, :if => :should_validate_password?   
  validates_confirmation_of :password, :if => :should_validate_password?   

  validates_presence_of :email
  validates_uniqueness_of :email      
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"

  def self.authenticate(username, pass)
    u=find(:first, :conditions=>["username = ?", username])
    return nil if u.nil?
    return u if User.encrypt(pass, u.salt)==u.hashed_password
  end 

  def password=(pass)
    @password=pass
    self.salt = User.random_string(10) if !self.salt?
    self.hashed_password = User.encrypt(@password, self.salt)
  end
  ####email service
  def comment_remind ( commenter)
      UserMailer.comment_review(self, commenter).deliver
  end
  def signup_confirmation
      UserMailer.signup_confirmation(self).deliver
  end

  def change_new_password
    new_pass = User.random_string(10)
    self.password = new_pass
    self.password_confirmation = new_pass
    self.save!
    #Notifications.deliver_forgot_password(self.email, self.username, new_pass)
    #No background process, because heroku charge for that
    self.send_password(self, new_pass)
  end
  ####conditinal validate
  def should_validate_password?   
      password_validator==true
  end

  def should_validate_username?
      username_validator==true
  end

  def change_password (current_password, new_password, new_password_confirmation)
     if user= User.authenticate(self.username, current_password)
        user.password = new_password
        user.password_confirmation = new_password_confirmation
        debugger
        return user.save
     else
        return false
     end

  end
  
  def send_password (user, password)
      UserMailer.send_password(user, password).deliver
  end

  def no_omniauth?
      self.provider.nil?
  end

  def self.from_omniauth(auth)
   
     user = where(auth.slice(:provider, :uid)).first
     if user.nil?
        user = find_by_email auth.info.email
        if user.nil?
           user = User.new
           user.provider = auth.provider
           user.uid = auth.uid      
           user.oauth_token = auth.credentials.token
           user.oauth_expires_at = Time.at(auth.credentials.expires_at)     
           user.username = auth.info.name     
           user.email = auth.info.email        
           user.web_page = auth.info.urls.Facebook
           user.location = auth.info.loation
           user.name = auth.info.name
           user.password_validator = false
           user.username_validator = false
           user.image = File.open ('app/assets/images/fb_avatar.jpg')
        
           user.save!
        end
     end
   
     return user
    
  end

  protected

  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest(pass+salt)
  end

  def self.random_string(len)
    #generat a random password consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
    return newpass
  end

  def self.setUser_type(usr)
  #  if rand(2) == 1
  #    usr.user_type = Moderator.to_s
  #  else
    usr.user_type = "Moderator"
  #  end
  end


end

Telephoenix/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
  make_flagger
  attr_accessible :user_id, :user_type
end

Telephoenix/app/controllers/user_controller.rb
class UserController < ApplicationController
  respond_to :html, :json
  before_filter :login_required, :only=>['welcome', 'change_password']


  def register
    @user = User.new(params[:user])
   # debugger
    @user.user_type = "User"
    #User.setUser_type(@user)

    if request.post?
      @user.image = File.open ('app/assets/images/fb_avatar.jpg')
      @user.password_validator = true
      @user.username_validator = true
      if @user.save
        session[:user_id] = User.authenticate(@user.username, @user.password).id
        flash[:message] = "Signup successful #{@user.user_type}"
       # debugger
        #send email for sign up
        @user.signup_confirmation
        
        redirect_to :controller => "phones" #TODO redirect to welcome page
      else
        flash[:warning] = "Signup unsuccessful"
      end
    end
  end

  def login
    if request.post?
      if User.authenticate(params[:user][:username], params[:user][:password])
        session[:user_id]= User.authenticate(params[:user][:username], params[:user][:password]).id
        usr = User.find_by_id(session[:user_id])
        username = usr.username
        usertype = usr.user_type
        flash[:message] = "Login successful"
       
        if moder?
          flash[:message] = "Hello Moderator #{username}"
          redirect_to user_indexMod_path
        elsif admin?
          flash[:message] = "Welcome Master #{username}"
          redirect_to user_indexAdmin_path
        else
          redirect_to_stored
        end
      else
        flash[:warning] = "Login unsuccessful"
      end
    end
  end

  def logout
    session[:user_id] = nil
    flash[:message] = "Logged out"
    redirect_to :action => "login"
  end
  
  def forget_password
    if request.post?
       user = User.find_by_email params[:user][:email]
   
       if  user.nil? == false          
           user.change_new_password
           flash[:message] = "You new password is being sended"
           redirect_to phones_path
       else
           flash[:message] = "Invalid email"
           redirect_to  user_forget_password_path
       end             
    end  
  end

  def change_password
    @user = User.find_by_id params[:id]  
    if request.post?
       if User.authenticate(@user.username, params[:user][:current_password])
         
          @user.password = params[:user][:password]
          @user.password_confirmation = params[:user][:password_confirmation] 
          @user.password_validator = true
          @user.username_validator = true
          if @user.save
             #debugger
            
             flash[:message] = "You password is changed successfully"
             redirect_to edit_user_path(@user)
          else
           flash[:message] = "You didn't change password successfully, please do it again"
           redirect_to change_password_user_path(@user)
          end

       else 
           flash[:message] = "You didn't change password successfully, please do it again"
           redirect_to change_password_user_path(@user)
       end
    end  
     
  end

  def  upgrade       
       @user = User.find_by_id params[:format]
       if (params[:kind] == "promote")
        @user.user_type = "Moderator"
        @user.save
        flash[:message] = "#{@user.username} has been promoted to a Moderator"
      elsif (params[:kind] == "demote")
        @user.user_type = "User"
        @user.save
        flash[:message] = "#{@user.username} has been demoted to a User"
      end

      if admin?
        redirect_to user_indexAdmin_path
      elsif
        redirect_to user_indexMod_path
      end
  end
  
  def edit
     @user = User.find(params[:id])
  end
   
  def  update
    @user = User.find(params[:id])
    @user.password_validator = false
    @user.username_validator = true
    @user.update_attributes(params[:user])
    respond_with @user, :location => edit_user_path

  end

  
  def destroy
    comments = Comment.find_all_by_user_id(params[:id])
    comments.each { |comment|
      comment.destroy}
    reviews = Review.find_all_by_user_id(params[:id])
    reviews.each { |review| 
      rcomments = Comment.find(:all, :from => "Comments", :conditions => ['review_id = ?',review.id])
      rcomments.each { |comment|
      comment.destroy}
      review.destroy}
    User.find(params[:id]).destroy
    flash[:message] = "The user has been deleted."
    redirect_to user_indexAdmin_path
  end


  def show
    @user = User.find(params[:id])
    @reviews = Review.find_all_by_user_id(params[:id])
    #debugger
  end

  def demoteModerator
    User.user_type = "User"
    User.save
  end

  def indexMod
    @users = User.where(:user_type => "User").all
    @reviews = nil
    @phones = Phone.all

  end

  def indexAdmin
    @moderators = User.where(:user_type => "Moderator").all
    @users = User.where(:user_type => "User").all
  end


end

Telephoenix/app/views/user/change_password.html.haml
%h2 Change Password

= form_tag change_password_user_path(@user), method: :post do
  = label :user, :username, "Current password"
  = password_field :user, :current_password
  
  = label :user, :password, "New password"
  = password_field :user, :password

  = label :user, :password_confirmation, "Confirm password"
  = password_field :user, :password_confirmation

  = submit_tag "Save changes"

Telephoenix/app/views/user/edit.html.haml
= stylesheet_link_tag 'user'
%h1=@user.username
%div.profile
  = image_tag @user.image_url(:thumb), :class => 'photo'
  = form_for @user, :html => {:multipart => true} do |f|
    %p Change Profile Picture
    = f.file_field :image, :class=>"image_input"
    %br
    = f.submit "Save"
  %p
    %b  Name:  
    = best_in_place @user, :name, :nil=> "click to input Name"
  %p
    %b Email: 
    = best_in_place @user, :email, :type => :input,:nil=> "click to input email address"
  %p
    %b Gender:
    = best_in_place @user, :gender, type: :select, collection: [["Male", "Male"], ["Female", "Female"], ["", "Unspecified"]]

  %p
    %b Location:
    = best_in_place @user, :location, :nil=>"click to input current location"
  
  %p.web_page
    %b Web Page:
    = best_in_place @user, :web_page, :nil=>"click to input personal web page"

  %section.interests
    %b Insterests:
    %br
    = best_in_place @user, :interest, type: :textarea, :nil=>"click to put your interests"
  %p
    %b Is your profile open to public ?
    =best_in_place @user, :public_profile, type: :checkbox, collection: %w[No Yes]
  %p= link_to "Change your password", change_password_user_path(@user)
    

Telephoenix/app/views/user/forget_password.html.haml
%h3 forget password


= form_tag user_forget_password_path, method: :post do
  = label :user, :email, "Email Address"
  = text_field :user, :email



  = submit_tag "submit"

Telephoenix/app/views/user/indexAdmin.html.haml
%h2 What would you like to do?

%table{:style => "width: 50%; height: 40%"}
  %tr
    %th 
      %b Supervise Moderators
    %th
      %b Assign Moderators
  %tbody
    %tr{:valign => "top"}
      %td
        %dl
          %dt{:valign => "center"}
          - if @moderators.empty?
            %dd
            = "No moderators to administrate"
          - @moderators.each do |moderator|
            %dd
              = moderator.username 
              %dl
                %dt
                  %dd
                    %div
                      %div{:style => "float:left"}
                        = button_to "Demote", user_upgrade_path(moderator, :kind => "demote"), confirm: 'Are you sure?'
                      %div{:style => "float:left"}
                        = "  |  "
                      %div{:style => "float:left"}  
                        = button_to "Delete User", user_path(moderator), method: :delete, confirm: 'Are you sure?'
                      %div{:style => "clear:both" }
                  %p
      %td
        %dl
          %dt
          - if @users.empty?
            %dd{:align => "center"}
            = "No users to administrate"
          - @users.each do |usr|
            %dd
              = usr.username 
              %dl
                %dt
                  %dd
                    %div
                      %div{:style => "float:left"}
                        = button_to "Promote", user_upgrade_path(usr, :kind => "promote"), confirm: 'Are you sure?'
                      %div{:style => "float:left"}
                        = "  |  "
                      %div{:style => "float:left"}  
                        = button_to "Delete User", user_path(usr), method: :delete, confirm: 'Are you sure?'
                      %div{:style => "clear:both" }

                  %p
    %tr
      %td= button_to "Back to Phones", phones_path 

Telephoenix/app/views/user/indexMod.html.haml
%h2 Administrating Moderators

%table{:style => "width:50%"}
  %tr
    %th{:align => "left"} 
      %b List of all Users:
    %th{:align => "left"}
      %b List of all Reviews:
  %tbody
    %tr
      %td{:valign => "top"}
        %dl
          %dt
          - if @users.empty?
            %dd
            = "No users to administrate"
          - elsif
            - @users.each do |usr|
              %dd
                = usr.username 
                %dl
                  %dt
                    %dd
                      %div                
                        %div{:style => "float:left"}
                          = button_to "Promote", user_upgrade_path(usr, :kind => "promote"), confirm: 'Are you sure?'
                        %div{:style => "float:left"}
                          = " | "
                        %div{:style => "float:left"}
                          = button_to "Delete User", user_path(usr), method: :delete, confirm: 'Are you sure?'
                      %div{:style => "clear:both" }       
                    %p 
      %td{:valign => "top"}
        %dl
        - @phones.each do |phone|
          - if !Review.find_all_by_phone_id(phone.id).empty?
            %dt
              %b= phone.name
              %dd{:valign => "top"}
              - @reviews = Review.find_all_by_phone_id(phone.id)
              - @reviews.each do |review|
                = review.review_text
                %dd{:margin => "100" }
                = link_to "View full review", phone_review_path(review.phone, review)
                = " | "
                ="by user "
                = link_to "#{review.user.username}", user_path(review.user)
                %p
    %tr
      %td= link_to "Back to Phones", phones_path

Telephoenix/app/views/user/login.html.haml
%h2 Login


= form_tag user_login_path, method: :post do
  = label :user, :username, "Username"
  = text_field :user, :username

  = label :user, :password, "Password"
  = password_field :user, :password

  = submit_tag "Login"
  = link_to "Register", user_register_path
  %br 
  %section
    = link_to "forget password?", user_forget_password_path

Telephoenix/app/views/user/register.html.haml
%h2 Register

= form_tag user_register_path, method: :post do
  = label :user, :username, "Username"
  = text_field :user, :username
  
  = label :user, :password, "Password"
  = password_field :user, :password

  = label :user, :password_confirmation, "Confirm Password"
  = password_field :user, :password_confirmation

  = label :user, :email, "Email"
  = text_field :user, :email

  = submit_tag "Register"

Telephoenix/app/views/user/show.html.haml
= stylesheet_link_tag 'user'
%h2= @user.username
- if !@user.public_profile&&session[:user_id]!=@user.id
  %p="#{@user.username}'s information is not open to all"
- else
  %div
    = image_tag @user.image_url(:thumb).to_s
    %p=@user.name.nil?  ?    "" :  "Name:#{@user.name}"
    %p=@user.email.nil?  ?   "" :  "Email:#{@user.email}"
    %p=@user.gender.nil?  ?  "" : "Gender:#{@user.gender}"
    %P=@user.location.nil? ? "" : "Location: #{@user.location}"
    %p=@user.web_page.nil? ? "" : "Web Page: #{@user.web_page}"
    %div.interests
      =@user.interest.nil? ? "" : "Insterests: #{@user.interest}"


%table#reviews
  %col{:width => "200px"}
  %thead
    %tbody
      - @reviews.each do |review|
        %tr
          %td= "Rating: " + review.rating.to_s
          %td
            = "Phone: "
            = link_to review.phone.name.to_s, phone_path(review.phone)
        %tr
          %td= "\t"
          %td= review.review_text.to_s             
          %td= link_to "View Comments (" + review.comments.count.to_s + ")", phone_review_path(review.phone, review)