Telephoenix/config/routes.rb
Telephoenix::Application.routes.draw do

  match 'auth/:provider/callback', to: 'omniauth#create'
  match 'auth/failure', to: redirect('/')
  

  get "static_pages/about"

  get "static_pages/contact"

  get "static_pages/home"

  resources :likes

  get "user/register"
  post "user/register"

  get "user/login"
  post "user/login"

  get "user/logout"

  get "user/delete"

  get "user/edit"

  get "user/forget_password"   
  post "user/forget_password"

  get "user/upgrade"
  post "user/upgrade"

  get "user/indexMod"
  get "user/indexAdmin"
  
  resources :user do
    member do
      get 'change_password'
      post 'change_password'
    end
  end

  

  
resources :phones do
    resources :reviews do
        resources :comments
    end
end

match "/review_likes/new/:review_id/:value"=> "review_likes#new"
resources :review_likes

resources :user

root to: redirect('/phones')
end

Telephoenix/app/models/phone.rb
class Phone < ActiveRecord::Base
  has_many :tags
  has_many :ratings
  has_many :reviews
  attr_accessible :id, :name, :brand, :imgurl
 


  def self.search (search)
  	find(:all, :select => "Phones.id, name, brand", :from => "Tags, Phones", :conditions => ['lower(value) LIKE lower(?) AND phone_id = Phones.id', "%" + search + "%"]) +
    find(:all, :select => "Phones.id, name, brand", :from => "Tags, Phones", :conditions => ['lower(key) LIKE lower(?) AND phone_id = Phones.id', "%" + search + "%"]) +
    find(:all, :conditions => ['lower(name) LIKE lower(?)', "%" + search + "%"]) +
    find(:all, :conditions => ['lower(brand) LIKE lower(?)', search])
  end
  
  def self.phones_choosen (args={})
      ##disply para
      sort_by = args[:sort_by]
      ##filter  para
      brands = args[:brands]
      os = args[:os]
      rating = args[:rating]
      ##filter & sort      
      phones = self.filter_by_brand(brands)&self.filter_by_os(os)&self.filter_by_rating(rating)
      phones = self.sort_by(phones, sort_by)      
  end
  
  def self.phones_on_page (phones, current_page, num_per_page)
      start = (current_page-1)*num_per_page
      tail = [self.count-1, current_page*num_per_page-1].min 
          
      phones[start .. tail]
       
  end

  def self.filter_by_brand (brands)  # brands=["brand1", "brand2"]      
      phones = brands.empty? ?  self.all : self.where(:brand => brands)            
  end
  
  def self.filter_by_os (os) # os=['os1' , 'os2'], must be in an array
      phones = []
      if os.empty? 
        phones = self.all
      else 
        os.each do |s|
           phones = phones + Phone.includes(:tags).where('tags.value LIKE ?', "%#{s}%")
        end
      end 
      return phones        
  end
  
  def self.filter_by_rating (rating)  #rating fixnum 20,40,60,80
      phones = self.all
      phones.find_all { |p|
         r = (p.overallRatings=='NA') ?  0 : p.overallRatings 
         r >= rating
      }     
  end
  
  def self.sort_by (phones, key) 
      if key== "brand" || key == :brand  
      phones.sort {|p1,p2| p1.brand.downcase<=>p2.brand.downcase}      
      elsif key== "rating" || key == :rating
      phones.sort {|p1,p2| 
         rating_1 = (p1.overallRatings =="NA") ? 0 : p1.overallRatings
         rating_2 = (p2.overallRatings =="NA") ? 0 : p2.overallRatings
      
         rating_2<=>rating_1
      } 
      else 
      end
      
  end
 
  def self.num_if_checked (phones, brands, os, ratings) #rating are determined  '4', '3', '2', '1'
       ratings = ['4', '3', '2', '1']
       num = {}
       brands.each {|brand|  num[brand] = (filter_by_brand(brand)&phones).count }
       os.each {|s| num[s] = (filter_by_os([s])&phones).count }
       ratings.each {|rating| num[rating] = (filter_by_rating(20*rating.to_i)&phones).count }
     
 
       return num
  end      

=begin 

  def self.sort_by (key)
      phones= self.all;
     if key== "brand" || key == :brand  
      phones.sort {|p1,p2| p1.brand.downcase<=>p2.brand.downcase}      
     elsif key== "rating" || key == :rating
      phones.sort {|p1,p2| 
         rating_1 = (p1.overallRatings =="NA") ? 0 : p1.overallRatings
         rating_2 = (p2.overallRatings =="NA") ? 0 : p2.overallRatings
      
         rating_2<=>rating_1
      } 
     else
      self.all             
     end
     
  end

=end

def num_stars ()
  num = self.overallRatings()
  num = num=="NA" ?  0 : num/20.0
end
  
def overallRatings()
  overall = 0
  total = 0
	ratings.each do |rating|
    if !rating.number_reviews
      overall += rating.rating*10
      total += 10
    else
		  overall += rating.rating*rating.number_reviews
      total += rating.number_reviews
    end
	end
  reviews.each do |review|
    overall += review.rating*10
    total += 1
  end
	return (total>0) ? overall/total : ("NA")
  end

  def proRating()
    overall = 0
    total = 0
    ratings.each do |rating|
      if !rating.number_reviews
        overall += rating.rating
        total += 1
      end
    end
    return (total>0) ? overall/total : ("NA")
  end

  def userRating()
    overall = 0
    total = 0
    ratings.each do |rating|
      if rating.number_reviews
        overall += rating.rating*rating.number_reviews
        total += rating.number_reviews
      end
    end
    reviews.each do |review|
      overall += review.rating*10
      total += 1
    end
    return (total>0) ? overall/total : ("NA")
  end

end

Telephoenix/app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def index
    @num_params = params[:show].nil? ?  {} : params[:show]
    @num_per_page = params[:show].nil? ?  20 : params[:show][:number].to_i
    
  
    @sort_by_params = params[:sort_by].nil? ?   {:word => :brand}  :  params[:sort_by]
 
    @current_page = params[:page].nil? ?  1 : params[:page].to_i 
  
    @brands_params = params[:brands].nil? ?  {} : params[:brands]
    @os_params = params[:os].nil? ? {} : params[:os]
    @ratings_params = params[:ratings].nil? ? {} : params[:ratings]
 
    ####fetch data: @sort_by is "brand"/"rating" 
    sort_by = params[:sort_by].nil? ?   "brand" : params[:sort_by][:word].downcase
    brands = @brands_params.keys
    os = @os_params.keys
    rating = @ratings_params.keys.empty? ? 0 : @ratings_params.keys[0].to_i*20   #make rating 0-100
    
    phones = Phone.phones_choosen :brands => brands, :os => os, :rating => rating, :sort_by => sort_by
   # debugger
    @num_all  = phones.count
    @num_pages = (@num_all.to_f/@num_per_page).ceil
    
    @phones = Phone.phones_on_page phones, @current_page, @num_per_page
    ####                 sort
    @select = []
    @select[0] = sort_by.capitalize
    @select[1] = sort_by=="brand" ? "Rating" : "Brand"
    ####                 items/page
    @select_num = []
    temp = [10, 20, 30]
    @select_num[0] = @num_per_page
    temp.each do |num| 
      if num!= @num_per_page
           @select_num << num
      end
    end
    ####                 pagination
    @pages_bar = []
    @pages_bar[1] = 1
    i = 1
    if @current_page<=4
       while i <= @current_page
          @pages_bar[i] = i
          i = i+1
       end
    else
       @pages_bar[2] = "..."
       @pages_bar[3 .. 4] = [@current_page-1, @current_page]
       i = 5
    end
    if @current_page< @num_pages-1
       @pages_bar[i .. i+2] = [@current_page+1, "...", @num_pages]
    elsif @current_page< @num_pages
       @pages_bar[i] = @current_page+1
    end 
    ####                     right column     
    ##             brands 
    temp = Phone.select("distinct brand")
    brands = []
    temp.each_index {|i| brands[i] = temp[i].brand}
    @brands1 = brands[0 .. 4]
    @brands2 = brands[5 .. -1]  
    @brands_checked = words_checked(brands, @brands_params)
        
    ##             operating system
    @os =["Android", "BlackBerry", "Brew", "IOS", "Symbian", "Windows Phone"]
    @os_checked = words_checked(@os, @os_params)

    ##              rating
    @ratings =["4","3","2","1"]      
    @ratings_checked = words_checked(@ratings, @ratings_params)
    ####              number of phones if checked
    @num_if_checked = {}
    @num_if_checked = Phone.num_if_checked(phones, brands, @os, @ratings)
    ##             number of reviews
    
  
  end

  def words_checked (words, words_params)
    words_checked = {}
    words.each do |w|
       words_checked[w] = words_params[w].nil? ? false : true
    end
    return words_checked
  end

  def show
    @phone = Phone.find(params[:id])
    @tags = Tag.find_all_by_phone_id(params[:id])
    @ratings = Rating.find_all_by_phone_id(params[:id])
    @reviews = Review.find_all_by_phone_id(params[:id])
    @overallrate = @phone.overallRatings()
    @prorating = @phone.proRating()
    @userrating = @phone.userRating()
  end

  def create
  	@phones = Phone.search(params[:name])
  end
end

Telephoenix/app/views/phones/create.html.haml
%h2 Search Results

%table#phones
  %thead
    %tr
      %th Brand
      %th Name
      %th Rating
    %tbody
      - @phones.each do |phone|
        %tr
          %td= phone.brand
          %td= link_to "#{phone.name}", phone_path(phone)
          %td
            %h3= phone.overallRatings().to_s+"%"

Telephoenix/app/views/phones/index.html.haml
= stylesheet_link_tag 'phones'
%h2 Browse Phones


%span="Showing #{(@current_page-1)*@num_per_page+1}-#{@current_page*@num_per_page} of #{@num_all} Results     " 


%table#phones
  %thead
    %tr
      %th
      %th Brand
      %th Name
      %th Rating
      -if !@phones.empty?
        -@phones.each do |phone|
          %tr
            %td= (phone.imgurl)? (image_tag phone.imgurl) : ""
            %td= phone.brand
            %td
              = link_to "#{phone.name}", phone_path(phone), :method => :get
            %td 
              %span.review
                =link_to image_stars(phone.num_stars()) ,  phone_path(phone), :class=>"aa" 
                = phone.overallRatings().to_s+"%"
                = "(#{phone.reviews.count}  reviews)"
              %div.float
                =link_to image_stars(phone.num_stars()) ,  phone_path(phone)
                = phone.overallRatings().to_s+"%"
                %br
                %br
                - reviews = (phone.reviews.order("num_likes DESC"))[0 .. 2]
                - if !reviews.empty?
                  -reviews.each do |review|
                    %section
                      = " \" #{review.review_text} \" "
                      %br
                      = (link_to "#{review.user.username}", user_path(review.user)) + content_tag(:span, (space(4)+'|'+space(4)+"#{review.num_likes} Likes"+space(8)+"#{review.num_dislikes} Dislikes").html_safe)
                      
                    %br
 


= link_to_unless  @current_page==1, "Previous Page",  phones_path(:show=> @num_params, :sort_by => @sort_by_params, :page=>(@current_page-1), :ratings => @ratings_params, :brands => @brands_params, :os => @os_params ) 

- @pages_bar.each do |p|
  = link_to_unless  @current_page==p||p=="...",  "#{p}", phones_path(:show=> @num_params, :sort_by=> @sort_by_params, :page=>p, :ratings => @ratings_params, :brands =>@brands_params, :os => @os_params ) 

=link_to_unless  @current_page==@num_pages||@num_pages==0,  "Next Page", phones_path(:show=> @num_params, :sort_by=> @sort_by_params, :page=>(@current_page+1), :ratings => @ratings_params, :brands => @brands_params, :os => @os_params ) 

%nav#R_col{:align => "right"}
  = form_tag phones_path, :method => :get, :id =>"side_col" do
    %section#Sort       
      = label :show, :number, "Show"
      = select :show, :number, @select_num, {}, :onchange => "$('#side_col').submit()"
      = label :sort_by, :word, "Sort by"
      = select :sort_by, :word, @select, {}, :onchange => "$('#side_col').submit()"
    %section#Brands
      %h4 Manufacturer          
      %section.Brands1
        - @brands1. each do |b|
          = check_box_tag name= "brands[#{b}]", value = 1, checked = @brands_checked[b], :class => "ratings", :onclick => "$('#side_col').submit()"
          = "#{b}"
          = content_tag(:span, "    (#{@num_if_checked[b]})", :class => 'num_if_checked') 
          %br
      %section.Brands2
        - @brands2. each do |b|
          = check_box_tag name= "brands[#{b}]", value = 1, checked = @brands_checked[b], :class => "ratings", :onclick => "$('#side_col').submit()"
          = "#{b}"
          = content_tag(:span, "   (#{@num_if_checked[b]})", :class => 'num_if_checked') 
          %br
      %p See more manufacturers
      
    %section#OSs
      %h4 Operating System
      - @os.each do |s|
        = check_box_tag name= "os[#{s}]", value = 1, checked = @os_checked[s], :class => "ratings", :onclick => "$('#side_col').submit()"
        = "#{s}"
        = content_tag(:span, "      (#{@num_if_checked[s]})", :class => 'num_if_checked') 
        %br
    %section#Ratings
      %h4 Overall Rating
      - @ratings.each do |r|    
        = check_box_tag name= "ratings[#{r}]", value = 1, checked = @ratings_checked[r], :class => "ratings"
        = image_stars(r.to_i)+content_tag(:span, "&UP") 
        = content_tag(:span, "      (#{@num_if_checked[r]})", :class => 'num_if_checked') 
        %br
     

Telephoenix/app/views/phones/show.html.haml
%h2= @phone.brand + ' ' + @phone.name
= (@phone.imgurl) ? (image_tag @phone.imgurl) : ""
%div
  %div{:style => "float:left"}
    = button_to "Back", {:controller => "phones", :action => "index" }, :method => :get
%div{:style => "clear:both"}

%ul#tags
  - @tags.each do |tag|
    %li= tag.key + ": " + tag.value

  - @ratings.each do |rating|
    %li= "Rating: " + rating.rating.to_s

%h4~ ("Pro Rating: " + @prorating.to_s)
%h4~ ("User Rating: " + @userrating.to_s)
%h3~ ("Overall Rating: " + @overallrate.to_s )

%table#reviews
  %thead
    %tr
      %th{:width => "250px"}
        TelePhoenix User Reviews
      %div
        %div{:style => "float:left"}
          %th= button_to "New Review", new_phone_review_path(@phone), :method => :get 
      %div{:style => "clear:both" }
    %tbody
    - @reviews.each do |review|
      %tr
        %td
          %dl
            %dt
              %dd
                = "User: "
                = link_to review.user.username.to_s, user_path(review.user)
              %dd
                = "Rating: " + review.rating.to_s
              %dl
                %dt
                  %dd
                    = review.review_text.to_s
          %td
      %tr      
        %td
        - current_user = User.find_by_id(session[:user_id])
        %td
          %dl  
            %dt
              %div
                %div{:style => "float:left"}
                  %dd
                  = button_to "#{review.num_likes} Likes", {:review_id =>review.id,  :value => "like",:method => "get", :action => "create", :controller => "review_likes" }
              %div{:style => "clear:both" }

              %div
                %div{:style => "float:left"}
                  %dd= button_to "#{review.num_dislikes} Dislikes", {:review_id =>review.id,  :value => "unlike",:method => "get", :action => "create", :controller => "review_likes" }
              %div{:style => "clear:both" }

              %div
                %div{:style => "float:left"}         
                  %dd= link_to "View Comments (" + review.comments.count.to_s + ")", phone_review_path(review.phone, review)
              %div{:style => "clear:both" }
          
 

      