Telephoenix/config/routes.rb
Telephoenix::Application.routes.draw do

  match 'auth/:provider/callback', to: 'omniauth#create'
  match 'auth/failure', to: redirect('/')
  

  get "static_pages/about"

  get "static_pages/contact"

  get "static_pages/home"

  resources :likes

  get "user/register"
  post "user/register"

  get "user/login"
  post "user/login"

  get "user/logout"

  get "user/delete"

  get "user/edit"

  get "user/forget_password"   
  post "user/forget_password"

  get "user/upgrade"
  post "user/upgrade"

  get "user/indexMod"
  get "user/indexAdmin"
  
  resources :user do
    member do
      get 'change_password'
      post 'change_password'
    end
  end

  

  
resources :phones do
    resources :reviews do
        resources :comments
    end
end

match "/review_likes/new/:review_id/:value"=> "review_likes#new"
resources :review_likes

resources :user

root to: redirect('/phones')
end

Telephoenix/app/views/layouts/application.html.haml
%html
  %head
    %title TelePhoenix
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
   
    %div#headbar
      = image_tag 'tplogo.png'
      %div#currentuser
        - if session[:user_id]
          - current_user = User.find_by_id(session[:user_id])        
          = image_tag current_user.image_url(:small), :class => "small_image"
          = link_to "Hello #{current_user.username} !", edit_user_path(current_user)
          - if admin?
            = link_to "Control Panel", user_indexAdmin_path
          - elsif moder?
            = link_to "Control Panel", user_indexMod_path
          = link_to "Logout", user_logout_path, :id => 'logout'
        - else
          = link_to (image_tag "fb_login.png", :class=>"fb_png"), '/auth/facebook', :id => 'login'
          = space(1).html_safe
          = link_to "Login", user_login_path
          |
          = link_to "Register", user_register_path
    %div#navbar
      = link_to "Home", static_pages_home_path
      = link_to "About" ,static_pages_about_path
      = link_to "Contact",static_pages_contact_path
      = link_to "Browse", phones_path
      = form_tag phones_path :class => "navbar-search pull-left", :method => :get do
        = text_field_tag :name, nil, :class => "search-query span3", :placeholder => "Search"
      %div#navClear
    - if flash[:message]
      %div#message
        = flash[:message]
    - if flash[:warning]
      %div#warning
        = flash[:warning]
  %div#content
    = yield